name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: configure
      run: .github/scripts/install_software.sh; sudo .github/scripts/init_vm_network.sh
    - name: STM32L475 Build
      run: cd demo/sample_azure_iot_embedded_sdk/stm32l4_l4+/ ; make
