name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: configure
      run: .build/install_softwares.sh
    - name: Linux Build
      run: cd demo/sample_azure_iot_embedded_sdk/linux/ ; make
    - name: STM32L475 Build
      run: cd demo/sample_azure_iot_embedded_sdk/stm32l475/ ; make
    - name: Run unit-tests
      run: cd tests ; cmake -Bbuild .; cmake --build build; cd build; ctest
